# Generated by Django 5.2 on 2025-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_careerassessmentquestion_careerassessmentanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_responses", models.TextField()),
                ("roadmap", models.TextField()),
                ("skills", models.TextField()),
                ("certifications", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="resource",
            name="roadmap",
        ),
        migrations.RemoveField(
            model_name="roadmap",
            name="user",
        ),
        migrations.DeleteModel(
            name="RequiredSkill",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Roadmap",
        ),
    ]
