# Generated by Django 5.2 on 2025-04-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="areas_of_interest",
            new_name="interests",
        ),
    ]
