# Generated by Django 5.2 on 2025-05-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_careerroadmap_remove_resource_roadmap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerassessmentquestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
