# Generated by Django 5.2 on 2025-05-07 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_careerassessmentquestion_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerroadmap",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_roadmaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
