# Generated by Django 5.2 on 2025-05-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_careerroadmap_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseRecommendation",
        ),
        migrations.RemoveField(
            model_name="skillassessment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="skillselfassessment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="members",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
        migrations.DeleteModel(
            name="SkillAssessment",
        ),
        migrations.DeleteModel(
            name="SkillSelfAssessment",
        ),
        migrations.DeleteModel(
            name="StudyGroup",
        ),
    ]
