# Generated by Django 5.2 on 2025-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_courserecommendation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerroadmap",
            name="content_markdown",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="roadmap",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="user_responses",
            field=models.JSONField(),
        ),
    ]
