# Generated by Django 5.2 on 2025-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_careerroadmap_content_markdown_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerroadmap",
            name="content_markdown",
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="certifications",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="roadmap",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="skills",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="careerroadmap",
            name="user_responses",
            field=models.TextField(),
        ),
    ]
